- id: '1674826775050'
  alias: Toggle Garage Heaters
  description: ''
  trigger:
  - platform: tag
    tag_id: 639abad5-b2b0-487f-a894-1f1f4f93e5de
  condition: []
  action:
  - type: toggle
    device_id: 214fe9d6428d9b66b2f797b112898f39
    entity_id: switch.garage_halogen_heater
    domain: switch
  - type: toggle
    device_id: 1b7af3eff0ca5891beb8cbeff6b14703
    entity_id: switch.garage_fan_heater
    domain: switch
  mode: single
- id: '1675515365804'
  alias: Lola Sleep
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 9a895010e39037b05ed9cd2c61ef9774
    entity_id: light.hue_lola_s_room
    domain: light
  - service: media_player.media_stop
    data: {}
    target:
      device_id: 3108f29ffae5beef401f318b9604e31f
  mode: single
