---
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

http:
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_key_path

mqtt:
  sensor:
    - name: Garage Thermometer Temperature
      state_topic: "govee/A4:C1:38:75:FE:24"
      value_template: "{{ value_json.temp_c }}"
      unit_of_measurement: "C"
    - name: Garage Thermometer Battery
      state_topic: "govee/A4:C1:38:75:FE:24"
      value_template: "{{ value_json.batt }}"
      unit_of_measurement: "%"

script: !include scripts.yaml
scene: !include scenes.yaml
