---
alias: "Lola's Bedroom - Do Not Disturb"
id: "lola_bedroom_do_not_disturb"
mode: single

trigger:
  - platform: state
    entity_id: schedule.lola_sleep

condition: []

action:
  - choose:
      - conditions:
          - alias: "When sleep starts"
            condition: state
            entity_id: schedule.lola_sleep
            state: "on"
        sequence:
          - type: turn_on
            device_id: 3108f29ffae5beef401f318b9604e31f
            entity_id: switch.lola_s_echo_do_not_disturb_switch
            domain: switch

      - conditions:
          - alias: "When sleep ends"
            condition: state
            entity_id: schedule.lola_sleep
            state: "off"
        sequence:
          - type: turn_off
            device_id: 3108f29ffae5beef401f318b9604e31f
            entity_id: switch.lola_s_echo_do_not_disturb_switch
            domain: switch
