---
alias: "Lola's Bedroom - Do Not Disturb"
id: "lola_bedroom_do_not_disturb"
mode: single

trigger:
  - platform: time
    id: &time_down "time_down"
    at: '21:00:00'
  - platform: time
    id: &time_up "time_up"
    at: '07:00:00'

condition: []

action:
  - choose:
      - conditions:
          - alias: "At night"
            condition: trigger
            id: *time_down
        sequence:
          - type: turn_on
            device_id: 3108f29ffae5beef401f318b9604e31f
            entity_id: switch.lola_s_echo_do_not_disturb_switch
            domain: switch

      - conditions:
          - alias: "In the morning"
            condition: trigger
            id: *time_up
        sequence:
          - type: turn_off
            device_id: 3108f29ffae5beef401f318b9604e31f
            entity_id: switch.lola_s_echo_do_not_disturb_switchh
            domain: switch
