---
alias: "Lola's Bedroom - Do Not Disturb"
id: "lola_bedroom_do_not_disturb"
mode: single

trigger:
  - platform: state
    entity_id: schedule.lola_lights_out

condition: []

action:
  - choose:
      - conditions:
          - alias: "When sleep starts"
            condition: state
            entity_id: schedule.lola_lights_out
            state: "on"
        sequence:
          - service: switch.turn_on
            data: { }
            target:
              entity_id: switch.lola_s_echo_do_not_disturb_switch

      - conditions:
          - alias: "When sleep ends"
            condition: state
            entity_id: schedule.lola_lights_out
            state: "off"
        sequence:
          - service: switch.turn_off
            data: { }
            target:
              entity_id: switch.lola_s_echo_do_not_disturb_switch
