---
alias: "Lola's Lights"
id: "lolas_light_automation"
mode: restart

trigger:
  - id: &motion_detected motion_detected
    platform: state
    entity_id:
      - binary_sensor.jake_s_room_sensor_motion
    from: "off"
    to: "on"

  - id: &at_sunset "at_sunset"
    platform: sun
    event: sunset
    offset: 0

  - id: &sleep_trigger sleep_trigger
    platform: state
    entity_id: schedule.lola_lights_out

  - id: &fallback_trigger fallback_trigger
    platform: time
    at: "22:00:00"

condition: []

variables:
  anchors:
    - &turn_on_low
      service: scene.turn_on
      data: {}
      target:
        entity_id: scene.lola_s_room_nightlight

    - &turn_on_high
      service: scene.turn_on
      data: {}
      target:
        entity_id: scene.lola_s_room_bright

    - &turn_off
      service: light.turn_off
      target:
        entity_id: light.lola_s_light

action:
  - choose:
      - conditions:
          - alias: "Motion detected at night"
            and:
              - alias: "When sleeping"
                condition: state
                entity_id: schedule.lola_lights_out
                state: "on"
              - alias: "Motion detected"
                condition: trigger
                id: *motion_detected
        sequence:
          - *turn_on_low
          - delay:
              minutes: 3
          - *turn_off

      - conditions:
          - alias: "At sunset"
            condition: trigger
            id: *at_sunset
        sequence:
          - *turn_on_high

      - conditions:
          or:
            - alias: "When sleep starts/stops"
              condition: trigger
              id: *sleep_trigger
            - alias: "On fallback trigger"
              condition: trigger
              id: *fallback_trigger
        sequence:
          - *turn_off
