---
alias: "Lola's Lights"
id: "lolas_light_automation"
mode: restart

trigger:
  - id: &motion_detected motion_detected
    platform: state
    entity_id:
      - binary_sensor.jake_s_room_sensor_motion
    from: "off"
    to: "on"

  - id: &at_sunset "at_sunset"
    platform: sun
    event: sunset
    offset: 0

  - id: &down_time "down_time"
    platform: time
    at: "21:00:00"

condition: []

variables:
  anchors:
    - &target
      target:
        device_id: 9a895010e39037b05ed9cd2c61ef9774

    - &turn_on_low
      service: light.turn_on
      <<: *target
      data:
        color_name: white
        brightness_pct: 25

    - &turn_on_high
      service: light.turn_on
      <<: *target
      data:
        color_name: white
        brightness_pct: 100

    - &dim_to_off
      service: light.turn_off
      <<: *target
      data:
        transition: 300

action:
  - choose:
      - conditions:
          - alias: "Motion detected after downtime"
            condition: and
            conditions:
              - alias: "After 9:00pm"
                condition: time
                after: "21:00:00"
              - alias: "Motion detected"
                condition: trigger
                id: *motion_detected
        sequence:
          - *turn_on_low
          - delay:
              minutes: 5
          - *dim_to_off

      - conditions:
          - alias: "At sunset"
            condition: trigger
            id: *at_sunset
        sequence:
          - *turn_on_high

      - conditions:
          - alias: "At downtime on school nights"
            condition: trigger
            id: *down_time
        sequence:
          - *dim_to_off
