---
alias: Lola Sleep
id: '1675515365804'
mode: single

trigger:
  - platform: state
    entity_id: schedule.lola_lights_out
    to: 'on'

condition: []

action:
  - service: media_player.media_stop
    data: { }
    target:
      entity_id: media_player.lola_s_echo
