---
alias: Lola Sleep
id: '1675515365804'
mode: single

trigger:
  - platform: time
    at: '21:00:00'

condition: []

action:
  - type: turn_off
    device_id: 9a895010e39037b05ed9cd2c61ef9774
    entity_id: light.hue_lola_s_room
    domain: light

  - service: media_player.media_stop
    data: {}
    target:
      device_id: 3108f29ffae5beef401f318b9604e31f
