---
alias: Jake Bedroom - Lights
id: "jakes_light_automation"
mode: restart

trigger:
  - id: &at_sunset "at_sunset"
    platform: sun
    event: sunset
    offset: 0

  - id: &bedtime "bedtime"
    platform: time
    at: input_datetime.jake_next_bedtime
    offset: 900

condition: []

variables:
  anchors:
    - &target
      target:
        entity_id: light.jake_s_light

    - &turn_on_high
      service: hue.activate_scene
      data: { }
      target:
        entity_id: scene.jake_s_room_bright

    - &dim_to_off
      service: light.turn_off
      <<: *target
      data:
        transition: 300

action:
  - choose:
      - conditions:
          - alias: "At sunset"
            condition: trigger
            id: *at_sunset
        sequence:
          - *turn_on_high

      - conditions:
          - alias: "At downtime on weekends"
            condition: trigger
            id: *bedtime
        sequence:
          - *dim_to_off
