---
alias: "Jake's Lights"
id: "jakes_light_automation"
mode: restart

trigger:
  - id: &at_sunset "at_sunset"
    platform: sun
    event: sunset
    offset: 0

  - id: &school_time_down "school_night_time_down"
    platform: time
    at: "20:45:00"

  - id: &weekend_time_down "weekend_time_down"
    platform: time
    at: "21:25:00"

condition: []

variables:
  anchors:
    - &target
      target:
        entity_id: light.jake_s_light

    - &turn_on_high
      service: light.turn_on
      <<: *target
      data:
        color_name: white
        brightness_pct: 100

    - &dim_to_off
      service: light.turn_off
      <<: *target
      data:
        transition: 300

action:
  - choose:
      - conditions:
          - alias: "At sunset"
            condition: trigger
            id: *at_sunset
        sequence:
          - *turn_on_high

      - conditions:
          - alias: "At downtime on school nights"
            condition: trigger
            id: *school_time_down
        sequence:
          - *dim_to_off

      - conditions:
          - alias: "At downtime on weekends"
            condition: trigger
            id: *weekend_time_down
        sequence:
          - *dim_to_off
