---
alias: Jake Bedroom - Set Next Bedtime
id: "65f924c3-4889-4c81-b402-9486820b9680"
mode: single

trigger:
  - platform: state
    entity_id: input_boolean.home_mode_school_night

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.home_mode_school_night
            state: "on"
        sequence:
          - service: input_datetime.set_datetime
            target:
              entity_id: input_datetime.jake_next_bedtime
            data:
              time: "20:30:00"

      - conditions:
          - condition: state
            entity_id: input_boolean.home_mode_school_night
            state: "off"
        sequence:
          - service: input_datetime.set_datetime
            target:
              entity_id: input_datetime.jake_next_bedtime
            data:
              time: "21:30:00"
