---
alias: "Garage - Thermostat"
id: "63e99fd3-c23a-443d-99d3-eb08f8c47ea7"
mode: queued

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - input_boolean.home_mode_away
      - input_boolean.home_mode_working

  - id: &heater_on "heater_on"
    platform: state
    entity_id: switch.garage_fan_heater
    from: "off"
    to: "on"
    for:
      seconds: 5

condition: []

variables:
  anchors:
    - &target
      target:
        entity_id: climate.garage

    - &turn_off
      <<: *target
      alias: "Turn off heating"
      service: climate.set_hvac_mode
      data:
        hvac_mode: "off"

    - &turn_on
      <<: *target
      alias: "Turn on heating"
      service: climate.set_hvac_mode
      data:
        hvac_mode: "heat"

    - &turn_up
      <<: *target
      alias: "Turn up garage heat"
      service: climate.set_temperature
      data:
        temperature: "{{ states('input_number.garage_target_temp')| float(15.5) }}"

action:
  - choose:
      - conditions:
          - alias: "When turned on and HVAC off"
            and:
              - condition: trigger
                id: *heater_on
              - condition: state
                entity_id: climate.garage
                attribute: hvac_action
                state: 'off'
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.garage_fan_heater

      - conditions:
          - alias: "When the house is in away mode"
            condition: state
            entity_id: input_boolean.home_mode_away
            state: "on"
        sequence:
          - *turn_off

      - conditions:
          - alias: "When the house enters working mode"
            condition: state
            entity_id: input_boolean.home_mode_working
            state: "on"
        sequence:
          - *turn_on
          - *turn_up

    default:
      - *turn_off
