---
alias: "Garage - Heater"
id: "c6cb4461-0434-44fa-b63d-90127acbcf30"
mode: single

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - id: "home_mode_working"
    platform: state
    entity_id: input_boolean.home_mode_working
    to: "off"

  - platform: state
    id: "safety_fallback"
    entity_id: switch.garage_halogen_heater
    to: "on"
    for:
      hours: 3

  - platform: tag
    id: &tag_scanned "tag_scanned"
    tag_id: cea7b1f9-685d-4be3-b51d-71ebecdef544

condition: []

variables:
  anchors:
    - &target
      target:
        entity_id: switch.garage_halogen_heater

    - &turn_off
      service: switch.turn_off
      <<: *target

    - &toggle
      service: switch.toggle
      <<: *target

action:
  - choose:
      - conditions:
          - alias: "When tagged scanned"
            condition: trigger
            id: *tag_scanned
        sequence:
          - *toggle

    default:
      - *turn_off
