---
alias: "Notify on Garage Climate"
id: "89052e25-cf49-4583-be63-ecb0633920cd"
mode: single

trigger:
  - platform: state
    id: &state_on "heat_on"
    entity_id:
      - climate.garage
    attribute: hvac_action
    from: "off"
    to: heat

  - platform: state
    id: &state_off "heat_off"
    entity_id:
      - climate.garage
    attribute: hvac_action
    from: heat
    to: "off"

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: *state_on
        sequence:
          - service: notify.mobile_app_s21
            data:
              title: Garage Climate
              message: Changed to heat

      - conditions:
          - condition: trigger
            id: *state_off
        sequence:
          - service: notify.mobile_app_s21
            data:
              title: Garage Climate
              message: Changed to off
