---
alias: "Notify on Garage Climate"
id: "89052e25-cf49-4583-be63-ecb0633920cd"
mode: single

trigger:
  - platform: state
    entity_id:
      - climate.garage
    attribute: hvac_action

condition: []

action:
  service: notify.mobile_app_s21
  data:
    title: Garage Climate
    message: Changed to {{ trigger.to_state.state }}
