---
alias: "Bedroom - Do Not Disturb"
id: "bedroom_do_not_disturb"
mode: single

trigger:
  - platform: state
    entity_id: input_boolean.home_mode_sleep

condition: []

action:
  - choose:
      - conditions:
          - alias: "At night"
            condition: state
            entity_id: input_boolean.home_mode_sleep
            state: "on"
        sequence:
          - service: switch.turn_on
            data: { }
            target:
              entity_id: switch.bedroom_echo_do_not_disturb_switch

      - conditions:
          - alias: "In the morning"
            condition: state
            entity_id: input_boolean.home_mode_sleep
            state: "off"
        sequence:
          - service: switch.turn_off
            data: { }
            target:
              entity_id: switch.bedroom_echo_do_not_disturb_switch
