---
alias: "Bedroom - Echo"
id: "ca7314e2-fd39-478f-a30b-f826809f9a40"
mode: single

trigger:
  - platform: state
    entity_id: input_boolean.home_mode_sleep

condition: []

action:
  - choose:
      - conditions:
          - alias: "At night"
            condition: state
            entity_id: input_boolean.home_mode_sleep
            state: "on"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.bedroom_echo_do_not_disturb_switch

      - conditions:
          - alias: "In the morning"
            condition: state
            entity_id: input_boolean.home_mode_sleep
            state: "off"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.bedroom_echo_do_not_disturb_switch
