---
alias: "Living Room - Lamp"
id: "a0b1c2d3-e4f5-6g7h-8i9j-0k1l2m3n4o5p"
mode: single

trigger:
  - platform: time
    id: &kitchen_echo_timer "kitchen_ echo_timer"
    at: sensor.kitchen_echo_show_next_timer

  - id: &on_sunset "sunset_trigger"
    platform: sun
    event: sunset
    offset: 0

  - id: &at_11 "time_trigger"
    platform: time
    at: "23:00:00"

  - id: &sleep_mode "sleep_mode"
    platform: state
    entity_id: input_boolean.home_mode_sleep
    to: "on"

condition: []

variables:
  anchors:
    - &target
      target:
        entity_id: light.living_room

    - &turn_on_high
      service: hue.activate_scene
      data: { }
      target:
        entity_id: scene.living_room_bright

    - &dim_to_off
      service: light.turn_off
      <<: *target
      data:
        transition: 300

    - &turn_off
      service: light.turn_off
      <<: *target

    - &create_before_scene
      service: scene.create
      data:
        scene_id: living_room_lamp_before
        snapshot_entities:
          - light.living_room

    - &flash
      service: light.turn_on
      <<: *target
      data:
        brightness_pct: 100
        flash: long

    - &restore_before_scene
      service: scene.turn_on
      target:
        entity_id: scene.living_room_lamp_before
action:
  - choose:
      - conditions:
          - alias: "On timer up"
            condition: trigger
            id: *kitchen_echo_timer
        sequence:
          - *create_before_scene
          - *flash
          - *restore_before_scene

      - conditions:
          - alias: "At sunset"
            condition: trigger
            id: *on_sunset
        sequence:
          - *turn_on_high

      - conditions:
          - alias: "At 11pm when away"
            condition: and
            conditions:
              - condition: trigger
                alias: "At 11pm"
                id: *at_11
              - condition: state
                entity_id: input_boolean.home_mode_away
                state: "on"
        sequence:
          - *dim_to_off

      - conditions:
          - alias: "Sleep mode"
            condition: trigger
            id: *sleep_mode
        sequence:
          - *turn_off
