---
alias: "Living Room Lamp"
id: "a0b1c2d3-e4f5-6g7h-8i9j-0k1l2m3n4o5p"
mode: single

trigger:
  - platform: sun
    event: sunset
    offset: 0

condition: []

action:
  - type: turn_on
    device_id: b982797d2f8328b6f858ea08e0811347
    entity_id: light.living_room
    domain: light
