---
alias: "Living Room TV"
id: "a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"
mode: single

trigger:
  - platform: state
    entity_id: input_boolean.home_mode_sleep
    to: "on"

condition: []

action:
  - service: media_player.turn_off
    data: { }
    target:
      device_id: 3b63bd8eb1c2f2b66ae9a1ad605877ed
  - service: media_player.turn_off
    data: { }
    target:
      device_id: f347ed341cd748aa5fa9b35370fd6d5e
