---
alias: "Living Room - TV"
id: "a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"
mode: single

trigger:
  - platform: state
    entity_id: input_boolean.home_mode_sleep
    to: "on"

condition: []

action:
  - service: media_player.turn_off
    data: { }
    target:
      entity_id: media_player.living_room_tv_3
  - service: media_player.turn_off
    data: { }
    target:
      entity_id: media_player.roku_yx00d5142159
