---
alias: Home Mode - Working
id: "1ab749ed-323e-480d-8bbb-472137af4fdf"
mode: single

trigger:
  - platform: time
    id: "fallback_trigger"
    at: "18:00:00"

  - platform: state
    entity_id: schedule.home_working

condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"

variables:
  anchors:
    - &target
      data:
        entity_id: input_boolean.home_mode_working

    - &turn_off
      alias: "Turn off Home Mode - Working"
      service: input_boolean.turn_off
      <<: *target

    - &turn_on
      alias: "Turn on Home Mode - Working"
      service: input_boolean.turn_on
      <<: *target

action:
  - choose:
      - conditions:
          - alias: "When work starts"
            condition: state
            entity_id: schedule.home_working
            state: "on"
        sequence:
          - *turn_on

    default:
      - *turn_off

