---
alias: Home Mode - Sleep
id: "72b92651-b498-4e14-99c8-e5260aa2b81b"
mode: single

trigger:
  - platform: time
    id: &time_up "time_up"
    at: "07:00:00"

  - platform: state
    id: &armed_home "armed_home"
    entity_id: alarm_control_panel.welling_alarm
    to: "armed_home"

condition: []

action:
  - choose:
      - conditions:
          - alias: "In the morning"
            condition: trigger
            id: *time_up
        sequence:
          - alias: "Turn off Home Mode - Sleep"
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.home_mode_sleep

      - conditions:
          - alias: "When alarm is armed_home"
            condition: trigger
            id: *armed_home
        sequence:
          - alias: "Turn on Home Mode - Sleep"
            service: input_boolean.turn_on
            data:
              entity_id: input_boolean.home_mode_sleep
