---
alias: "Toggle Home Mode - Away"
id: "toggle_home_mode_away"
mode: single

trigger:
  - platform: state
    id: &away "away"
    entity_id: zone.home
    to: "0"
    for:
      minutes: 15

  - platform: state
    id: &home "home"
    entity_id: zone.home
    to: "1"

  - platform: state
    id: &alarm_armed "alarm_armed"
    entity_id: alarm_control_panel.welling_alarm
    to: "armed_away"
    for:
      minutes: 1

condition: []

variables:
  anchors:
    - &target
      data:
        entity_id: light.garden

    - &turn_off
      service: input_boolean.turn_off
      <<: *target

    - &turn_on
      service: input_boolean.turn_on
      <<: *target

action:
  - choose:
      - conditions:
          - alias: "When entering home"
            condition: trigger
            id: *home
        sequence:
          - *turn_off

      - conditions:
          - alias: "When away for 15 minutes"
            condition: trigger
            id: *away
        sequence:
          - *turn_on

      - conditions:
          - alias: "When alarm is armed"
            condition: trigger
            id: *alarm_armed
        sequence:
          - *turn_on
