---
alias: Home Mode - School Night
id: 6f667a77-53e4-4702-b28b-1c8f9c884c34
mode: single

trigger:
  - platform: calendar
    id: &event_start "event_start"
    entity_id: calendar.school_holidays
    event: start
    offset: "-12:00:00"

  - platform: time
    at: "0:00:00"

condition: []

variables:
  anchors:
    - &target
      data:
        entity_id: input_boolean.home_mode_school_night

    - &turn_off
      service: input_boolean.turn_off
      <<: *target

    - &turn_on
      service: input_boolean.turn_on
      <<: *target

  calendar_on:
    "{{ states('calendar.school_holidays') == 'on' }}"

  next_event_end:
    "{{ as_local(as_datetime(state_attr('calendar.school_holidays', 'end_time'))) }}"

  next_midnight:
    "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) + timedelta(days=1) }}"

  is_weekend:
    "{{ now().isoweekday() in [5, 6] }}"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: *event_start
            alias: "When school holidays start"
        sequence:
          - *turn_off

      - conditions:
          - condition: template
            alias: "When weekend"
            value_template: "{{ is_weekend }}"
        sequence:
          - *turn_off

      - conditions:
          - condition: template
            alias: "When school holidays"
            value_template: "{{ calendar_on and next_midnight != next_event_end }}"
        sequence:
          - *turn_off

    default:
      - *turn_on
