---
alias: "Home Mode - Working"
id: "1ab749ed-323e-480d-8bbb-472137af4fdf"
mode: single

trigger:
  - platform: state
    entity_id: schedule.home_working

action:
  choose:
    - conditions:
        - alias: "When work starts"
          condition: state
          entity_id: schedule.home_working
          state: "on"
      sequence:
        - alias: "Turn on Home Mode - Working"
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.home_mode_working

    - conditions:
        - alias: "When work ends"
          condition: state
          entity_id: schedule.home_working
          state: "off"
      sequence:
        - alias: "Turn off Home Mode - Working"
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.home_mode_working
