---
alias: "Toggle - Cameras"
id: "toggle_cameras"
mode: single

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    id: &when_away "when_away"
    entity_id:
      - input_boolean.home_mode_away
    to: "on"

  - id: &fallback_trigger fallback_trigger
    platform: time
    at: "18:00:00"

condition: []

variables:
  anchors:
    - &target
      target:
        entity_id: alarm_control_panel.blink_home

    - &turn_on
      service: alarm_control_panel.alarm_arm_away
      data: { }
      <<: *target

    - &turn_off
      service: alarm_control_panel.alarm_disarm
      <<: *target
      data: { }

action:
  - *turn_on
