---
alias: "Notify - Thermostats"
id: "4ceddd7e-aa01-4a27-9096-892e63251672"
mode: queued

trigger:
  - platform: state
    entity_id:
      - climate.garage
      - climate.living_room
      - climate.bedroom
      - climate.bedroom_lola
      - climate.bedroom_jake
      - climate.dining_room
      - climate.landing
    attribute: hvac_action

condition:
  - condition: state
    entity_id: "input_boolean.kill_switch_notify_climate"
    state: "on"

action:
  service: notify.mobile_app_s23_ultra
  data:
    title: "{{ trigger.to_state.name }} HVAC Changed"
    message: "From {{ trigger.from_state.attributes.hvac_action }} to {{ trigger.to_state.attributes.hvac_action }} ({{ trigger.to_state.attributes.temperature }})"
