---
alias: "Notify on Climate"
id: "4ceddd7e-aa01-4a27-9096-892e63251672"
mode: queued

trigger:
  - platform: state
    entity_id:
      - climate.hall
      - climate.garage
    attribute: hvac_action

condition: []

action:
  service: notify.mobile_app_s23_ultra
  data:
    title: Climate Changed
    message: {{ trigger.to_state.name }} to {{ trigger.to_state.state }}
