---
alias: "Notify on Timer Up"
id: "notify_on_timer_up"
mode: queued

trigger:
  - platform: time
    at: sensor.kitchen_echo_show_next_timer

condition: []

action:
  service: notify.mobile_app_s23_ultra
  data:
    message: "{{ trigger.to_state.name }} timer up"
