---
alias: Notify - Jake Bedtime
id: "2bfe144b-3dc3-43b7-b605-7a3131cfec48"
mode: single

trigger:
  - platform: time
    at: input_datetime.jake_next_bedtime

condition: []

action:
  - service: notify.alexa_media_living_room_echo
    data:
      message: Jake, brush your teeth, please.
      data:
        type: announce
        method: all

  - service: notify.alexa_media_jake_s_echo
    data:
      message: Jake, brush your teeth, please.
      data:
        type: tts
