---
alias: Notify - Jake Bedtime
id: "2bfe144b-3dc3-43b7-b605-7a3131cfec48"
mode: single

trigger:
  - platform: time
    at: input_datetime.jake_next_bedtime

condition: []

action:
  - service: notify.alexa_media
    data:
      target:
        - media_player.living_room_echo
      message: <speak><voice name="Brian">Hey, Jakey Jingles, it's your bedtime. Go and brush your teeth.<break time='10s'/>That means <emphasis level='strong'>NOW</emphasis>.</voice></speak>
      data:
        type: announce
        method: all

  - service: notify.alexa_media_jake_s_echo
    data:
      message: <speak><voice name="Brian">Hey, Jakey Jingles, it's your bedtime. Go and brush your teeth.<break time='10s'/>That means <emphasis level='strong'>NOW</emphasis>.</voice></speak>
      data:
        type: tts
