---
alias: "Garden - Lights"
id: "garden_light_automation"
mode: restart

trigger:
  - id: "at_sunset"
    platform: sun
    event: sunset
    offset: 0

  - id: "at_sunrise"
    platform: sun
    event: sunrise
    offset: 0

  - id: "at 11pm"
    platform: time
    at: "23:00:00"

  - id: &back_door_opened "back_door_opened"
    platform: state
    entity_id:
      - binary_sensor.back_door
    from: "off"
    to: "on"

  - id: "back_door_closed"
    platform: state
    entity_id:
      - binary_sensor.back_door
    from: "on"
    to: "off"

  - id: &motion_detected "motion_detected"
    platform: state
    entity_id:
      - binary_sensor.garden_sensor_motion
    from: "off"
    to: "on"

condition: []

variables:
  anchors:
    - &target
      target:
        area_id: garden

    - &after_sunset
      condition: sun
      after: sunset
      before: sunrise

    - &night_light
      service: hue.activate_scene
      data: { }
      target:
        entity_id: scene.garden_nightlight

    - &turn_on_high
      service: hue.activate_scene
      data: { }
      target:
        entity_id: scene.garden_bright

    - &dim_to_off
      service: light.turn_off
      <<: *target
      data:
        transition: 60

action:
  - choose:
      - conditions:
          - alias: "Backdoor opened and after sunset"
            condition: and
            conditions:
              - condition: trigger
                id: *back_door_opened
              - <<: *after_sunset
        sequence:
          - *turn_on_high

      - conditions:
          - alias: "Motion detected after sunset"
            condition: and
            conditions:
              - condition: trigger
                id: *motion_detected
              - <<: *after_sunset
        sequence:
          - *turn_on_high
          - *dim_to_off

      - conditions:
          - alias: "After 11pm and before sunrise"
            condition: time
            after: "10:59:59"
            before: sensor.sun_next_dawn
        sequence:
          - *night_light

      - conditions:
          - alias: "After sunset and before sunrise"
            <<: *after_sunset
        sequence:
          - *turn_on_high

    default:
      - *dim_to_off
