---
sensor:
  - platform: filter
    name: Filtered Garage Temperature
    entity_id: sensor.garage_thermometer_temperature
    filters:
      - filter: throttle
        window_size: 10
        precision: 2
