---
binary_sensor:
  - platform: workday
    country: GB
    province: England
    workdays: [mon, tue, wed, thu, fri]
    add_holidays:
      - '2023-02-15'
      - '2023-02-16'
      - '2023-02-17'
      - '2023-02-27'
