---
alias: "Dining Room - Dehumidifier"
id: "dining-room-dehumidifier"
mode: single

trigger:
  - id: "sleep_mode"
    platform: state
    entity_id: input_boolean.home_mode_sleep
    to: "on"

condition: []

variables:
  anchors:
    - &target
      target:
        entity_id: switch.bot_6e77

    - &turn_off
      service: switch.turn_off
      <<: *target

action:
  - *turn_off
